### ISSUE TITLE
`Error: Idl(MissingOrInvalidProgramItems("account mod: struct not found"))` when running `trident inti`

### ISSUE THREAD

**Issue by cryptopapi997** [Ackee-Blockchain/trident#160]
Hey guys, 

I have a project using Anchor 0.30.0 on which I'm trying to run `trident init`. An important specification here is I have `anchor-spl` as a dependency and I have it as version 0.30.0 as downgrading to 0.29.0 (like the docs recommend) would break everything in my program. Additionally, I tested a different 0.30.0 program with anchor-spl at 0.30.0 as well and there it worked fine.

My issue is, when I try to run `trident init` on this project it keeps giving me `Error: Idl(MissingOrInvalidProgramItems("account mod: struct not found"))`. I tried checking the source code, but I'm not exactly sure what this error means exactly. I tried deleting most of my program so that all that gets generated as an idl is the below, but still the same issue. Any tips on how to fix this?

```
{
  "address": "85R8U76mZMurovUW3Houj4oeJ4W3SH6PXbJuHoMzbQDZ",
  "metadata": {
    "name": "my_program",
    "version": "0.1.0",
    "spec": "0.1.0"
  },
  "docs": [
    "Some docs"
  ],
  "instructions": [],
  "errors": [
    {
      "code": 6000,
      "name": "MyError1"
    },
    {
      "code": 6001,
      "name": "MyError2"
    },
    {
      "code": 6002,
      "name": "MyError3"
    },
    {
      "code": 6003,
      "name": "MyError4"
    }
  ]
}
```

**Comment by lukacan** [comment]
Hello, we will look into it, do you have the source code available in any repository? :)

**Comment by Ikrk** [comment]
The problem is in the name of the context struct `InitPersistentMXE` which is converted by Anchor to kebab case as `init_persistent_mxe` and then by Trident back to camel case as `InitPersistentMxe` which does not correspond to the original name and is thus not found. 

As a temporary workaround, if you rename `InitPersistentMXE` to `InitPersistentMxe`, then the Trident initialization works.
