### ISSUE TITLE
Feature request - Adding programs to local validator genesis

### ISSUE THREAD

**Issue by meltedblocks** [Ackee-Blockchain/trident#169]
Would be great to have an option to add programs to local validator genesis during tests. When trying Trident I stumbled upon a problem with programs that integrate with Metaplex programs. As such are not added to validator genesis by default.

Ideally, Trident should have the option to add programs the same as Anchor does it - example `Anchor.toml`:
```
[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "genesis/metaplex_token_metadata_program.so"
```

Overall, great experience with using this tool so far. Cheers

**Comment by lukacan** [comment]
Hey @meltedblocks , thanks for the feedback ! Yes, we are preparing this type of feature.
